// This file is automatically generated from your CSS. Any edits will be overwritten.
export const playerList: string;
export const show: string;
export const selected: string;
export const player: string;
export const playerName: string;
export const playerColor: string;
export const playerGoals: string;
