// This file is automatically generated from your CSS. Any edits will be overwritten.
export const actionMenu: string;
export const button: string;
export const items: string;
export const show: string;
