// This file is automatically generated from your CSS. Any edits will be overwritten.
export const main: string;
export const pitch: string;
export const line: string;
export const btnLeft: string;
export const btnRight: string;
