// This file is automatically generated from your CSS. Any edits will be overwritten.
export const main: string;
export const pitch: string;
export const btnReload: string;
export const btnPrint: string;
export const printSheet: string;
